version: "3"

# Define the services/containers to be run
services:
  client: # name of the client or app service
    build: NFL-Pickem
    ports:
      - "4200:4200" # specify port forwarding
    volumes:
      - ./NFL-Pickem:/app # allows changes to client app to be reflected in the container

  server: # name of the server service
    build:
      context: NFL-Pickem-server
      dockerfile: Dockerfile-dev
    ports:
      - "3200:3200" # specify port forwarding
    links:
      - database # link this server service to the database service

  database: # name of the database service
    image: mongo
    ports:
      - "27017:27017" # specify port forwarding
